print('Desafio 02')
print('===================================================================')
print('Crie um script Python que leia o dia, o mês e o ano de nascimento')
print('de uma pessoa e mostre uma mensagem com a data formatada.')
print('===================================================================')
dia=input('Que dia você nasceu? ')
mes=input('Que mês você nasceu? ')
ano=input('Que ano você nasceu? ')
print('Sua data de aniversario é', dia+'/'+mes+'/'+ano)
print('===================================================================')