print('Desafio 03')
print('===================================================================')
print('Crie um script Python que leia dois números')
print(' e tente mostrar a soma entre eles.')
print('===================================================================')
n1=int(input('Digite um valor para o N1: '))
n2=int(input('Digite um valor para o N2: '))
n3=n1+n2
print('A soma entre N1 e N2 é igual a:',n3)
print('===================================================================')