print('Desafio 01')
print('===================================================================')
print('Crie um script Python que leia o nome de uma pessoa')
print('e mostre uma mensagem de boas-vindas de acordo com o valor digitado.')
print('===================================================================')
nome=input('Qual é o seu nome? ')
print('Olá', nome+'. Prazer em te conhecer!')
print('===================================================================')